# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a38adc37ddda2a401e71345425fe29325459af1537785b255f839c36d07cf284862ef5828fd3d324b82ce4c79ff8bcac8f9d6d9368bc702c8b599afe06d0265d

test:
  secret_key_base: fa6cff2f19b768b38da1fbb464a8095ed0a6c84889c18b9f872c94ed6f5fcd9341c570a8b34ae6f2349f019c7ea36c4464d6693ff431ba71439539dc2850a089

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
